#!/usr/bin/env bash
declare -r TODO_ROOT="$HOME/.todo"
declare -r TASK_FILE="${TODO_ROOT}/tasks"

if [[ $# -eq 0 ]]; then
  echo "usage: todo <init|list|add|edit|remove|mark|unmark> [args]"
fi

if [[ $1 == 'init' ]]; then
  mkdir -p "$TODO_ROOT"
  touch "$TASK_FILE"
  echo "Initialized successfully"
fi

if [[ ! -f "$TASK_FILE" ]]; then
  echo "Please run 'todo init' before running '$1' command."
fi

if [[ $1 == 'list' ]]; then
  echo "# To be done"
  grep '^[0-9]' "$TASK_FILE"
  echo "# Completed"
  echo "Empty"
fi

if [[ $1 == 'add' ]]; then
  shift
  declare -r TASK_TITLE="$*"

  declare LAST_TASK_ID
  LAST_TASK_ID=$(tail -n1 "$TASK_FILE" | cut -d' ' -f1 | grep -o '[0-9]')
  declare -r LAST_TASK_ID

  declare -r TASK_ID=$(( LAST_TASK_ID + 1 ))
  echo "$TASK_ID $TASK_TITLE" >>"$TASK_FILE"
fi

if [[ $1 == 'edit' ]]; then
  declare -r TASK_ID="$2"
  shift 2
  declare -r TASK_TITLE="$*"

  if ! grep --silent "^${TASK_ID} " "$TASK_FILE"; then
    echo "Task not found!"
    exit 1
  fi

  sed -i '' "s/^${TASK_ID} .*/${TASK_ID} ${TASK_TITLE}/" "$TASK_FILE"
fi

if [[ $1 == 'remove' ]]; then
  for TASK_ID in "$@"; do
    sed -i '' "s/^${TASK_ID} /-&/" "$TASK_FILE"
  done
fi