#!/usr/bin/env bash
declare -r TODO_ROOT="$HOME/.todo"
declare -r TASK_FILE="${TODO_ROOT}/tasks"

if [[ $# -eq 0 ]]; then
  echo "usage: todo <init|list|add|edit|remove|mark|unmark> [args]"
fi

if [[ $1 == 'init' ]]; then
  mkdir -p "$TODO_ROOT"
  touch "$TASK_FILE"
  echo "Initialized successfully"
fi

if [[ ! -f "$TASK_FILE" ]]; then
  echo "Please run 'todo init' before running '$1' command."
fi

if [[ $1 == 'list' ]]; then
  echo "# To be done"
  cat "$TASK_FILE"
  echo "# Completed"
  echo "Empty"
fi

if [[ $1 == 'add' ]]; then
  shift
  declare -r TASK_TITLE="$*"

  declare -r LAST_TASK_ID=$(cat "$TASK_FILE" | tail -n1 | cut -d' ' -f1)
  declare -r TASK_ID=$(( LAST_TASK_ID + 1 ))
  echo "$TASK_ID $TASK_TITLE" >>"$TASK_FILE"
fi

if [[ $1 == 'edit' ]]; then
  declare -r TASK_ID="$2"
  shift 2
  declare -r TASK_TITLE="$*"

  sed "s/^${TASK_ID} .*/${TASK_ID} ${TASK_TITLE}/" "$TASK_FILE"
fi